[package]
name = "constellation-extraction"
version.workspace = true
edition.workspace = true

[dependencies]
constellation-graph.workspace = true
constellation-resolution.workspace = true
rustc-hash.workspace = true
tree-sitter.workspace = true
tree-sitter-css.workspace = true
tree-sitter-html.workspace = true
tree-sitter-javascript.workspace = true
tree-sitter-python.workspace = true

[lints]
workspace = true

[dev-dependencies]
divan.workspace = true
insta.workspace = true

[[bench]]
name = "parse"
harness = false
