[package]
name = "constellation-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "constellation"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
constellation-graph.workspace = true
constellation-index.workspace = true
constellation-mcp.workspace = true
constellation-store.workspace = true
dirs.workspace = true
mimalloc.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
toml.workspace = true

[build-dependencies]
ico.workspace = true
resvg.workspace = true
winresource.workspace = true
