//! The built-in Django template tag and filter names, the exclusion tables the
//! template extractor consults so a `{% if %}` or a `|date` never becomes a
//! dangling `UsesTag` reference.

/// The built-in Django template tags (and the `{% end... %}` closers and clause
/// words a leaf/block tag node can surface), none of which a project defines, so a
/// `UsesTag` reference to one would only be permanent noise. A tag not listed is a
/// custom `{% my_tag %}` from a `{% load %}`-ed library, resolved to its
/// `@register.simple_tag`/`inclusion_tag` function by name.
pub(crate) const TEMPLATE_BUILTIN_TAGS: &[&str] = &[
    "autoescape",
    "block",
    "blocktrans",
    "blocktranslate",
    "comment",
    "csrf_token",
    "cycle",
    "debug",
    "elif",
    "else",
    "empty",
    "endautoescape",
    "endblock",
    "endblocktrans",
    "endblocktranslate",
    "endcomment",
    "endfilter",
    "endfor",
    "endif",
    "endifchanged",
    "endspaceless",
    "endverbatim",
    "endwith",
    "extends",
    "filter",
    "firstof",
    "for",
    "if",
    "ifchanged",
    "include",
    "load",
    "lorem",
    "now",
    "plural",
    "regroup",
    "resetcycle",
    "spaceless",
    "static",
    "templatetag",
    "trans",
    "translate",
    "url",
    "verbatim",
    "widthratio",
    "with",
];

/// The built-in Django template filters plus the `humanize` contrib set, excluded
/// from `UsesTag` references for the same reason as the built-in tags. A filter not
/// listed is a custom `@register.filter`.
pub(crate) const TEMPLATE_BUILTIN_FILTERS: &[&str] = &[
    "add",
    "addslashes",
    "apnumber",
    "capfirst",
    "center",
    "cut",
    "date",
    "default",
    "default_if_none",
    "dictsort",
    "dictsortreversed",
    "divisibleby",
    "escape",
    "escapejs",
    "filesizeformat",
    "first",
    "floatformat",
    "force_escape",
    "get_digit",
    "intcomma",
    "intword",
    "iriencode",
    "join",
    "json_script",
    "last",
    "length",
    "length_is",
    "linebreaks",
    "linebreaksbr",
    "linenumbers",
    "ljust",
    "lower",
    "make_list",
    "naturalday",
    "naturaltime",
    "ordinal",
    "phone2numeric",
    "pluralize",
    "pprint",
    "random",
    "rjust",
    "safe",
    "safeseq",
    "slice",
    "slugify",
    "stringformat",
    "striptags",
    "time",
    "timesince",
    "timeuntil",
    "title",
    "truncatechars",
    "truncatechars_html",
    "truncatewords",
    "truncatewords_html",
    "unordered_list",
    "upper",
    "urlencode",
    "urlize",
    "urlizetrunc",
    "wordcount",
    "wordwrap",
    "yesno",
];
